### PR TITLE
allow branch names and not just version numbers

### PR DESCRIPTION
**Pull request by seb-wahl**
allow branch names and not just version numbers
set --user flag for pip (required on blogin), doesn't hurt to have it everywhere else

### CODE REVIEW

**Comment by pgierz** [comment]
Could you put a usage example? I'll include it in the documentation

**Comment by seb-wahl** [comment]
```bash
esm_versions upgrade esm_environment=allow-source-workaround
```
or
```bash
esm_versions upgrade esm_environment=v4.0.1
```

**Comment by seb-wahl** [comment]
I could merge myself :-) but I did not for two reasons:
- having someone else check my modifications is always good
- I haven't run `bumpversion` on `esm_versions`. (Could you send me your bump version config or your recipe how you bump versions, so I can do this myself in the future)

**Comment by pgierz** [comment]
Agreed on both points :-)

Check the `setup.cfg` for the bumpversion config:

```
[bumpversion]
current_version = 4.1.0
commit = True
tag = True

[bumpversion:file:setup.py]
search = version="{current_version}"
replace = version="{new_version}"

[bumpversion:file:esm_version_checker/__init__.py]
search = __version__ = "{current_version}"
replace = __version__ = "{new_version}"
```

If you just run `bumpversion <major|minor|patch>` in the top level, it'll take care of:
1) New version numbers in all relevant files
2) Tag with the new version number

I've been trying to follow semantic versioning for the version number scheme, so major for "breaking changes", minor for "new features" and patch for "bugfixes"

**Comment by seb-wahl** [comment]
I'll merge this now, as I need it to proceed with testing and porting to new machines. Otherwise I always have to "hack" e.g. `esm-environments` before I can start testing foci. With this update I can manage branches with `esm_versions`. I'm sure it's useful for others, too.

**Comment by pgierz** [comment]
Sorry for the delay, it was still on my list. I'll put your other PR in now.

**Pull request merged**
